name: tuttest-test

on: [push, pull_request]

jobs:
  test-sphinx-docs:
    runs-on: ubuntu-18.04
    env:
      LANG: "en_US.UTF-8"
      DOCKER_NAME: test
      IN_DOCKER_EXEC: "docker exec -t test bash -e -c"

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Setup Docker
        run: |
            docker create --name $DOCKER_NAME -v $PWD:$PWD --workdir $PWD --tty ubuntu:bionic
            docker start $DOCKER_NAME

      - name: Install tuttest
        run: |
            sudo locale-gen $LANG
            pip3 install git+https://github.com/antmicro/tuttest#egg=tuttest

      - name: Direct call
        run: tuttest xc7/counter_test/README.rst nonexisting-snippet | ${IN_DOCKER_EXEC} "$(cat /dev/stdin)"

      - name: Indirect call
        run: bash .github/scripts/tuttest-test.sh | ${IN_DOCKER_EXEC} "$(cat /dev/stdin)"
